browser=chrome
url=http://localhost:8080/parabank/index.htm

username=admin
password=admin

# Wait Configuration (Seconds) Note: after stable pls remove from enums
explicit.wait=20
page.load.timeout=30

# Browser Configuration
headless=false

execution=local
grid.url=http://localhost:4444/wd/hub

# Screenshot Configuration
take.screenshot.on.pass=false
take.screenshot.on.fail=true